# Generated by Django 5.2.8 on 2026-03-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
