# Generated by Django 6.0.3 on 2026-03-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_contactrequest_agent_email_contactrequest_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='agents/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('deals', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['name'],
            },
        ),
    ]
