# Generated by Django 5.2.8 on 2026-03-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deal', 'Deal Story'), ('event', 'Event'), ('news', 'Market News')], max_length=20)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('text', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date'],
            },
        ),
    ]
