# Generated by Django 6.0.3 on 2026-03-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tag',
        ),
    ]
