# Generated by Django 6.0.3 on 2026-03-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_blogpost_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('deals', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('is_agent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
