# Generated by Django 6.0.3 on 2026-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_teammember_delete_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
