# Generated by Django 6.0.3 on 2026-03-25 04:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_category_remove_blogpost_type_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#C9A84C', image_field=None, max_length=25, samples=None),
        ),
    ]
